services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    image: selfhost/jupyterlab-quarto:latest
    container_name: jupyterlab
    restart: unless-stopped

    command:
      - start-notebook.py
      - --NotebookApp.token=
      - --NotebookApp.password=
      - --ServerApp.root_dir=/home   # opens at top level

    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=1000
      - NB_GID=100                 # keep in sync with host user
      - DOCKER_GID=984 # pass host docker group id via .env if needed

    volumes:
      # user notebooks / configs
      - ./jupyter-home:/home/jovyan
      # host project trees (adjust host paths if different)
      - /home/chris/repos:/home/chris/repos # This is an example of a folder on the host that you want to be able to edit from jupyter.
      # give the container control of the host docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

    # allow UID=1000 to talk to /var/run/docker.sock
    group_add:
      - "984"

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP Router – redirect to HTTPS
      - "traefik.http.routers.jupyterlab.entrypoints=web"
      - "traefik.http.routers.jupyterlab.rule=Host(`jupyterlab.crispychrisprivserver.org`)"
      - "traefik.http.routers.jupyterlab.middlewares=redirect-to-https"

      # HTTPS Router – secured by Authentik + secure headers
      - "traefik.http.routers.jupyterlab-secure.entrypoints=websecure"
      - "traefik.http.routers.jupyterlab-secure.rule=Host(`jupyterlab.crispychrisprivserver.org`)"
      - "traefik.http.routers.jupyterlab-secure.tls=true"
      - "traefik.http.routers.jupyterlab-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.jupyterlab-secure.middlewares=authentik,secure-headers"
      - "traefik.http.routers.jupyterlab-secure.service=jupyterlab-service"

      # Service Port (internal 8888)
      - "traefik.http.services.jupyterlab-service.loadbalancer.server.port=8888"

networks:
  proxy:
    external: true
