services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565" 
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "TRUE" # Ensures only authenticated users can join
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "your_name, friends_name"  # Replace with real usernames
      OPS: "admin_username"                       # Optional: Add yourself as operator
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"     # Optional: for remote control (via env file or secret)
      MAX_PLAYERS: "10"
      MOTD: "Welcome to Your Server!"
      MEMORY: "4G" # Recommended
    volumes:
      - ./minecraft-data:/data
    tty: true
    stdin_open: true
    networks:
      - minecraft-net

networks:
  minecraft-net:
    driver: bridge
